table collections {
  id text [pk, not null]
  name text [not null]
  description text
  color text
  icon text
  order integer [default: 1]
  parentId text
  ownerId text [not null]
  createdAt text [default: `(CURRENT_TIMESTAMP)`]
  updatedAt text

  indexes {
    (name, ownerId) [name: 'collections_name_ownerId_unique', unique]
  }
}

table links {
  id text [pk, not null]
  url text [not null]
  title text
  description text
  previewImage text
  favicon text
  views integer [default: 0]
  lastVisit text [default: `(CURRENT_TIMESTAMP)`]
  isPinned integer [default: 0]
  collectionId text [not null]
  ownerId text [not null]
  createdAt text [default: `(CURRENT_TIMESTAMP)`]
  updatedAt text
}

table links_to_tags {
  id text [pk, not null]
  linkId text [not null]
  tagId text [not null]

  indexes {
    (linkId, tagId) [name: 'links_to_tags_linkId_tagId_unique', unique]
  }
}

table tags {
  id text [pk, not null]
  name text [not null]
  order integer [not null, default: 1]
  ownerId text [not null]
  createdAt text [default: `(CURRENT_TIMESTAMP)`]
  updatedAt text

  indexes {
    (name, ownerId) [name: 'tags_name_ownerId_unique', unique]
  }
}

table users {
  id text [pk, not null]
  firstName text
  lastName text
  password text [not null]
  email text [not null, unique]
  locale text [default: 'en']
  username text [not null, unique]
  isActive integer
  createdAt text [default: `(CURRENT_TIMESTAMP)`]
  updatedAt text
}

table users_to_collections {
  id text [pk, not null]
  userId text [not null]
  collectionId text [not null]

  indexes {
    (userId, collectionId) [name: 'users_to_collections_userId_collectionId_unique', unique]
  }
}

ref: collections.ownerId - users.id

ref: links.ownerId > users.id

ref: links.collectionId - collections.id

ref: links_to_tags.linkId > links.id

ref: links_to_tags.tagId > tags.id

ref: tags.ownerId > users.id

ref: users_to_collections.userId > users.id

ref: users_to_collections.collectionId > collections.id